### ISSUE TITLE
Criar um classe de abstração para as criptografias #TODO

### ISSUE THREAD

**Issue by PedroBicudo** [PedroBicudo/CriptografiaAPS#1]
- [x] Criar classe de abstração
- [x] Adicionar método de obtenção de criptografias 
- [x] Adicionar métodos abstração de criptografar e descriptografar
