### ISSUE TITLE
Refatorar cifra de César #TODO

### ISSUE THREAD

**Issue by PedroBicudo** [PedroBicudo/CriptografiaAPS#2]
- [x] Criar classe da Cifra de César que herda de [AbstractCriptModel](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/AbstractCriptModel.py);
- [x] Adicionar métodos privados para tratamento de texto;
- [x] Adicionar métodos de criptografia e descriptografia;
- [x] Inserir criptografia no arquivo [argumentos](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/argumentos.py);
- [x] Adicionar testes unitários.
