### ISSUE TITLE
Refatorar Cifra de Vigenere #TODO

### ISSUE THREAD

**Issue by PedroBicudo** [PedroBicudo/CriptografiaAPS#3]
- [x] Criar classe da Cifra de Vigenere que herda de [AbstractCriptModel](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/AbstractCriptModel.py);
- [x] Adicionar métodos privados para tratamento de texto;
- [x] Adicionar métodos de criptografia e descriptografia;
- [x] Inserir criptografia no arquivo [argumentos](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/argumentos.py);
- [x] Adicionar testes unitários;
- [x] Adicionar Docstring na classe.
