### ISSUE TITLE
Refatorar criptografia RSA #TODO

### ISSUE THREAD

**Issue by PedroBicudo** [PedroBicudo/CriptografiaAPS#6]
- [ ] Criar classe da criptografia RSA que herda de [AbstractCriptModel](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/AbstractCriptModel.py);
- [ ] Adicionar métodos privados para tratamento de texto;
- [ ] Adicionar métodos de criptografia e descriptografia;
- [ ] Inserir criptografia no arquivo [argumentos](https://github.com/PedroBicudo/CriptografiaAPS/blob/master/criptografiaAps/argumentos.py);
- [ ] Adicionar testes unitários;
- [ ] Adicionar Docstring na classe.
